export const allowedCountries = [
    "AD",
    "AL",
    "AT",
    "AZ",
    "BE",
    "BA",
    "BG",
    "HR",
    "CY",
    "CZ",
    "DK",
    "EE",
    "FI",
    "FR",
    "GE",
    "DE",
    "GI",
    "GR",
    "GG",
    "HU",
    "IS",
    "IE",
    "IM",
    "IT",
    "JE",
    "KZ",
    "XK",
    "LV",
    "LI",
    "LT",
    "LU",
    "MT",
    "MK",
    "MD",
    "MC",
    "ME",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "SM",
    "RS",
    "SK",
    "SI",
    "ES",
    "SJ",
    "SE",
    "CH",
    "UA",
    "GB",
    "VA",
] as const;

export const allowedCountriesAsObj = {
    AD: "Andorra",
    AL: "Albania",
    AT: "Austria",
    AZ: "Azerbaijan",
    BE: "Belgium",
    BA: "Bosnia and Herzegovina",
    BG: "Bulgaria",
    HR: "Croatia",
    CY: "Cyprus",
    CZ: "Czechia",
    DK: "Denmark",
    EE: "Estonia",
    FI: "Finland",
    FR: "France",
    GE: "Georgia",
    DE: "Germany",
    GI: "Gibraltar",
    GR: "Greece",
    GG: "Guernsey",
    HU: "Hungary",
    IS: "Iceland",
    IE: "Ireland",
    IM: "Isle of Man",
    IT: "Italy",
    JE: "Jersey",
    KZ: "Kazakhstan",
    XK: "Kosovo",
    LV: "Latvia",
    LI: "Liechtenstein",
    LT: "Lithuania",
    LU: "Luxembourg",
    MT: "Malta",
    MK: "North Macedonia",
    MD: "Moldova",
    MC: "Monaco",
    ME: "Montenegro",
    NL: "Netherlands",
    NO: "Norway",
    PL: "Poland",
    PT: "Portugal",
    RO: "Romania",
    SM: "San Marino",
    RS: "Serbia",
    SK: "Slovakia",
    SI: "Slovenia",
    ES: "Spain",
    SJ: "Svalbard and Jan Mayen",
    SE: "Sweden",
    CH: "Switzerland",
    UA: "Ukraine",
    GB: "United Kingdom",
    VA: "Vatican City",
};
